### ISSUE TITLE
Extract String helpers to separate addon

### ISSUE THREAD

**Issue by poteto** [DockYard/ember-composable-helpers#175]

**Comment by taras** [comment]
What do you think about turning `ember-composable-helpers` into an organization and pulling all of the helper addons under it's umbrella?

**Comment by romulomachado** [comment]
Extracted to [romulomachado/ember-cli-string-helpers](https://github.com/romulomachado/ember-cli-string-helpers). I wasn't really sure where to put, I hope there isn't a problem with it being on my profile. 

`ember-string-helpers` was already registered to NPM, that's why the `cli`. 😞 

Working on removing all String helpers from this addon rn.

**Comment by romulomachado** [comment]
✅  Done.

![](https://media.giphy.com/media/DgY4J4qV0acw/giphy.gif)
