### ISSUE TITLE
Bug: not compatible with ember-cli 2.11.0

### ISSUE THREAD

**Issue by IgorKvasn** [DockYard/ember-composable-helpers#249]
## Version

1.1.3 (latest)

## Test Case

simple ember project [here](https://github.com/IgorKvasn/ember-composable-helpers-bug)
just clone it and run `ember s`

## Steps to reproduce

- create a new Ember CLI project (must be version 2.11.0)
- add ember-composable-helpers addon
- run `ember s`

## Expected Behavior

ember-cli server should start without a problem

## Actual Behavior

ember-cli fails to start with an error: 

> Using ember-cli-shims as both a bower dependency and an npm dependency is not supported. Please remove `ember-cli-shims` from `bower.json`.

(in newest ember-cli, `ember-cli-shims` is a NPM package)

**Comment by martndemus** [comment]
This should be fixed now. Reopen if it isn't

**Comment by denchen** [comment]
Hello, it seems like `ember-cli-shims` is still being installed in bower. I'm on `ember-cli@2.11.0`. Here's how my installation looked like (I first removed `ember-composable-helpers` in `package.json` and removed it from `node_modules/`):

    % ember install ember-composable-helpers
    installing ember-composable-helpers
    install bower package ember-cli-shims
    cached https://github.com/ember-cli/ember-cli-shims.git#0.1.3
    cached https://github.com/components/ember.git#2.11.0
    Installed browser packages via Bower.
    Installed addon package.

*HOWEVER*, if I remove my `bower.json` first, then I get:

    % ember install ember-composable-helpers
    installing ember-composable-helpers
    install bower package ember-cli-shims
    WARNING: Skipping bower install: bower.json not found
    Installed addon package.

I have a `bower.json` because some of my packages still require a Bower install, even on Ember@2.11.0.
