### ISSUE TITLE
sorting behaviour changes in sort-by helper with version 4.1.0

### ISSUE THREAD

**Issue by stopfstedt** [DockYard/ember-composable-helpers#369]
## Version
4.1.0, 4.1.1

## Test Case
version 4.0.0
https://ember-twiddle.com/d09648cf6683649f390c74abedcfcc44?numColumns=3&openFiles=controllers.application%5C.js%2Ctemplates.application%5C.hbs%2Ctwiddle%5C.json

version 4.1.0
https://ember-twiddle.com/51cdad55b7daafd31226ed6426f5fe98?numColumns=3&openFiles=controllers.application%5C.js%2Ctemplates.application%5C.hbs%2Ctwiddle%5C.json

## Steps to reproduce
Use the `sort-by` helper on items with a given property that has text values.

## Expected Behavior
lowercase come before uppercase.

## Actual Behavior
uppercase comes before lowercase.

ref #362

**Comment by snewcomer** [comment]
I guess the old implementation was case insensitive 🤔.  The new implementation must be case sensitive.  Do you have a sense which one is more correct?  In any case, this is a breaking change, so should be fixed but curious on your opinion.  

This was the old implementation.
`import { sort } from '@ember/object/computed';`

**Comment by stopfstedt** [comment]
we've been waffling over this as well - is this a feature or a bug?
i'm leaning towards re-issuing a release with the new implementation, since it mirrors the behaviour of native JS sort. `computed.sort` should probably be realigned with this as well, but that's another conversation.

**Comment by snewcomer** [comment]
Thanks for the response.  Ya I agree.  The core issue here seems to be (intentional or not) whether the sorting is ASCII(betical) vs Alphabetical.  Ember's `sort` seems to be Alphabetical (case insensitive, perhaps more aligned with how the human mind works.  Whereas the native JS sort is ASCII(betical).

**Comment by jrjohnson** [comment]
Maybe use [String.localeCompare](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare)? It can be used without a locale option and hands off the implementation to the browser. This handles the case of 
1,2,10,11 being sorted as 1,10,11,2 as well (which is nice since no human thinks that is correct 😁).

**Comment by stopfstedt** [comment]
digging into the ember source code, it looks like that `computed.sort` is using `localeCompare` underneath the hood as well.

https://github.com/emberjs/ember.js/blob/7676db612c554ce49b1c6917762e0242e6c5d802/packages/%40ember/-internals/runtime/lib/compare.js#L119

granted, this is TypeScript (which i don't know much about), but i would assume that this behaves the same as JavaScript's `String.prototype.localeCompare()`.

**Comment by snewcomer** [comment]
You are probably right.  I mean...I don't know if there is a right answer.  Alphabetical might be closer to the human mind.  However, ASCII(betical) is how native JS does it.  Perhaps we should stick to Alphabetical (so as to not introduce breaking changes in `4.0`).  What do you think?

@jrjohnson Would you be ok diverging from how native JS handles it?  I think you are right.  The human mind does not expect this.

```js
['a1', 'b2', 'a100'].sort() === ["a1", "a100", "b2"]
```

**Comment by jrjohnson** [comment]
As I'm thinking of it I actually use `sort-by` in some paces to GET the natural alphabetical sort order. I was a bit stuck on the uppercase / lowercase part of this, but I do 100% prefer that this helper do natural alphabetical sort over the native JS comparison since the purpose is to put it in front of humans in a template.

**Comment by snewcomer** [comment]
@jrjohnson Does `localeCompare` handle alphanumeric properly?

```
'10'.localeCompare('2') === -1
```

```
toLocaleCompare(['1', '11', '2', '100']) === ['1', '100', '11', '2']
```

Or is this what you expect?

**Comment by jrjohnson** [comment]
Yes, I would have expected the second one too.

Oh - MDN has it as `a.localeCompare(b)`. Is this backwards? Maybe it doesn't matter? I always have to write tests for this because I never get the sorting comparison order right.

**Comment by jrjohnson** [comment]
@snewcomer I found the answer in our code. There is an option `{numeric: true}`

From MDN:
```
// by default, "2" > "10"
console.log("2".localeCompare("10")); // 1

// numeric using options:
console.log("2".localeCompare("10", undefined, {numeric: true})); // -1

```
